services:
  ganache:
    build:
      context: .
      dockerfile: Dockerfile.ganache
    container_name: cz-ganache
    ports:
      - "8545:8545"
    networks:
      - cznet

  truffle:
    build:
      context: .
      dockerfile: Dockerfile.truffle
    container_name: cz-truffle
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - ganache
    networks:
      - cznet

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: cz-frontend
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - ganache
    networks:
      - cznet

networks:
  cznet:
    driver: bridge
